# Generated by Django 5.0.6 on 2024-07-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_menutable_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='inventory',
            field=models.BooleanField(),
        ),
    ]
